name: UnitTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download native SDK
      run: wget https://github.com/SCVready/meta-presence/releases/download/release_v1.0/presenceos_1.0_native_sdk.tar -q

    - name: Extract native SDK
      run: tar -xvf presenceos_1.0_native_sdk.tar 

    - name: Install native SDK
      run: ./poky-glibc-x86_64-presenceos-core2-32-toolchain-2.6.4.sh -y -d ./native_sdk

    - name: Build Tests
      working-directory: ${{github.workspace}}
      run: source native_sdk/environment-setup-core2-32-poky-linux;cd test;mkdir -p build;cd build;cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}};make

    - name: Test
      working-directory: ${{github.workspace}}/test/build
      run: ../../native_sdk/sysroots/core2-32-poky-linux/lib/ld-linux.so.2 --library-path "../../native_sdk/sysroots/core2-32-poky-linux/lib/:../../native_sdk/sysroots/core2-32-poky-linux/usr/lib/" ./detection_tests



